version: '3'

services:
  assess:
    image: gradle:7-jdk17
    volumes:
      - "./assess:/app"
    working_dir: /app
    entrypoint: gradle --no-daemon bootRun
    ports:
      - "8080:8080"

  patient:
    image: gradle:7-jdk17
    volumes:
      - "./patient:/app"
    working_dir: /app
    entrypoint: gradle --no-daemon bootRun
    ports:
      - "8081:8081"

  historic:
    image: gradle:7-jdk17
    volumes:
      - "./historic:/app"
    working_dir: /app
    entrypoint: gradle --no-daemon bootRun
    ports:
      - "8082:8082"

  database:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: db
      MYSQL_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_ROOT_PASSWORD: admin

  mongo:
    image: mongo
    restart: always

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8180:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/