version: '3'

services:
  assess:
    build:
      context: ./assess/
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"

  patient:
    build:
      context: ./patient/
      dockerfile: ./Dockerfile
    ports:
      - "8081:8081"
    environment:
      # le module patient doit attendre que la base MySQL soit prête
      WAIT_HOSTS: database:3306
      WAIT_TIMEOUT: 300

  historic:
    build:
      context: ./historic/
      dockerfile: ./Dockerfile
    ports:
      - "8082:8082"
    environment:
      # le module historique doit attendre que la base MongoDB soit prête
      WAIT_HOSTS: mongo:27017
      WAIT_TIMEOUT: 300

  database:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: db
      MYSQL_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_ROOT_PASSWORD: admin

  mongo:
    image: mongo
    restart: always

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8180:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/